# Generated by Django 4.1.3 on 2022-11-30 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="tablename",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Institute_Code", models.TextField(max_length=300)),
                ("Program_code", models.TextField(max_length=300)),
                ("Type", models.TextField(max_length=300)),
                ("Institute_Name", models.TextField(max_length=300)),
                ("Degree_Name", models.TextField(max_length=300)),
                ("Category", models.TextField(max_length=300)),
                ("Branch", models.TextField(max_length=300)),
            ],
        ),
    ]
