# Generated by Django 4.1.3 on 2022-11-30 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("adminpage", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="tablename",
            new_name="Course",
        ),
    ]
