# Generated by Django 4.1.3 on 2022-11-30 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("adminpage", "0002_rename_tablename_course"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Course",
        ),
    ]
