# Generated by Django 4.1.3 on 2022-12-04 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("adminpage", "0003_delete_course"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student_details",
            fields=[
                (
                    "enrollment",
                    models.CharField(max_length=16, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=70, null=True)),
                ("sem", models.CharField(max_length=20, null=True)),
                ("phone", models.CharField(max_length=10, null=True, unique=True)),
                ("roll", models.CharField(blank=True, max_length=10, null=True)),
                ("oldenrollment", models.CharField(max_length=16, null=True)),
                ("email", models.CharField(max_length=70, null=True)),
                ("gender", models.CharField(max_length=1, null=True)),
                ("dob", models.DateField(null=True)),
                ("caste", models.CharField(max_length=20, null=True)),
                ("subcast", models.CharField(max_length=20, null=True)),
                ("category", models.CharField(max_length=10, null=True)),
                ("password", models.CharField(max_length=30, null=True)),
                ("photo", models.CharField(max_length=20, null=True)),
                ("institute_code", models.CharField(max_length=6, null=True)),
                ("program_code", models.CharField(max_length=6, null=True)),
                ("parent_contact", models.CharField(max_length=10, null=True)),
                ("emergency_contact", models.CharField(max_length=10, null=True)),
                ("userid", models.CharField(max_length=20, null=True)),
                ("address", models.CharField(max_length=200, null=True)),
                ("aadhaar", models.CharField(max_length=12, null=True)),
                ("finalsem", models.CharField(max_length=10, null=True)),
                ("term_end", models.CharField(max_length=4, null=True)),
                ("total_credits", models.FloatField(null=True)),
                ("total_grade_points", models.FloatField(null=True)),
                ("total_backlog", models.IntegerField(null=True)),
            ],
        ),
    ]
