# Generated by Django 4.1.3 on 2022-12-04 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("adminpage", "0004_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Student_details",
            new_name="StudentDetails",
        ),
    ]
