# Generated by Django 4.1.3 on 2022-12-04 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminpage", "0006_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="institute_Code",
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name="course",
            name="program_code",
            field=models.CharField(max_length=6),
        ),
    ]
