# Generated by Django 4.1.3 on 2022-12-06 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminpage", "0007_alter_course_institute_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentdetails",
            name="dob",
            field=models.DateTimeField(null=True),
        ),
    ]
