# Generated by Django 4.1.3 on 2022-12-06 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("adminpage", "0015_studentmarks"),
    ]

    operations = [
        migrations.DeleteModel(
            name="StudentMarks",
        ),
    ]
