# Generated by Django 4.1.3 on 2022-12-06 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminpage", "0016_delete_studentmarks"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentMarks",
            fields=[
                (
                    "enrollment",
                    models.CharField(max_length=16, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("subjectcode", models.CharField(max_length=10)),
                ("sem", models.IntegerField()),
                ("subjectname", models.CharField(max_length=20)),
                ("throry", models.BooleanField()),
                ("throry_marks", models.IntegerField()),
                ("practical", models.BooleanField()),
                ("practical_marks", models.IntegerField()),
                ("mid", models.BooleanField()),
                ("mid_marks", models.IntegerField()),
                ("institute_code", models.CharField(max_length=6, null=True)),
                ("program_code", models.CharField(max_length=6, null=True)),
            ],
        ),
    ]
