# Generated by Django 4.1.3 on 2022-12-06 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminpage", "0017_studentmarks_subject"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subject",
            name="id",
        ),
        migrations.AlterField(
            model_name="subject",
            name="subjectcode",
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
