# Generated by Django 4.1.3 on 2022-12-06 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("adminpage", "0019_alter_subject_mid_alter_subject_mid_marks_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subject",
            old_name="throry",
            new_name="theory",
        ),
        migrations.RenameField(
            model_name="subject",
            old_name="throry_marks",
            new_name="theory_marks",
        ),
    ]
