# Generated by Django 4.1.3 on 2022-12-07 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("adminpage", "0020_rename_throry_subject_theory_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentdetails",
            name="total_backlog",
        ),
    ]
