# Generated by Django 4.1.3 on 2022-12-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminpage", "0021_remove_studentdetails_total_backlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentdetails",
            name="total_backlog",
            field=models.IntegerField(null=True),
        ),
    ]
