# Generated by Django 4.1.3 on 2022-12-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminpage", "0022_studentdetails_total_backlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="grade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("percentage", models.IntegerField()),
                ("gradepoint", models.FloatField()),
                ("grade", models.CharField(max_length=6)),
                ("gradeclass", models.CharField(max_length=50)),
            ],
        ),
    ]
