# Generated by Django 4.1.3 on 2022-12-09 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("adminpage", "0029_studentdetails"),
    ]

    operations = [
        migrations.DeleteModel(
            name="StudentMarks",
        ),
    ]
