# Generated by Django 3.0.5 on 2023-09-17 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0002_auto_20230918_0000'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='YourModel',
            new_name='MyModel',
        ),
    ]
